// Per-site identity + seed content. The ONLY file that differs between sites.
import { makeArticle } from "./lib/seed";

export const SITE = {
  name: "Gulf Jobs Guide",
  lead: "Plan your next",
  accent: "Gulf Career Move",
  tagline: "Practical English guides for job seekers targeting the UAE, Saudi Arabia, Oman, Qatar, Kuwait, and Bahrain.",
  eyebrow: "Gulf careers · Practical job search guides",
  nav: ["CV", "Visas", "Interviews", "Job Portals"],
  defaultTheme: "royal",
  domain: "jobs.skoolai.cloud",

  seedArticles: [
    makeArticle({
      slug: "gulf-cv-format-for-uae-saudi-qatar-jobs",
      title: "Gulf CV Format: What Recruiters Expect",
      category: "CV", date: "2026-06-29", author: "Gulf Jobs Desk",
      excerpt: "Build a clear, recruiter-friendly CV for UAE, Saudi, Qatar, Oman, Kuwait, and Bahrain applications.",
      tags: ["cv", "resume", "gulf-jobs"],
      lead: "A Gulf job search usually starts with a fast CV screening. Recruiters need to understand your role, industry, visa status, location, and key skills in seconds.",
      takeaway: "A strong Gulf CV is direct, keyword-friendly, and honest about experience, availability, and visa status.",
      sections: [
        { h: "What to include first", p: ["Put the details recruiters use to shortlist near the top."],
          list: ["Current location and target Gulf country", "Mobile number with country code", "Email and LinkedIn URL", "Notice period or availability", "Relevant certifications and languages"] },
        { h: "Make your experience easy to scan", p: ["Use role titles, company names, dates, and measurable responsibilities. Avoid generic lines that could describe any job."],
          list: ["Start bullets with action verbs", "Mention tools, systems, or equipment", "Match keywords from the job description", "Keep claims accurate and verifiable"] },
      ],
      conclusion: "Tailor one clean CV for each role type, then update it before every serious application.",
    }),
    makeArticle({
      slug: "work-visa-basics-for-gulf-job-seekers",
      title: "Work Visa Basics for Gulf Job Seekers",
      category: "Visas", date: "2026-06-25", author: "Gulf Jobs Desk",
      excerpt: "Understand the safe basics of employer sponsorship, offer letters, and documents before accepting a Gulf role.",
      tags: ["visas", "offers", "gulf"],
      lead: "Visa rules differ across the UAE, Saudi Arabia, Oman, Qatar, Kuwait, and Bahrain, but one principle stays the same: legitimate employment should follow official procedures.",
      takeaway: "Never pay for guaranteed-job promises or shortcuts. Verify the employer, offer, and process before sharing money or documents.",
      sections: [
        { h: "Documents commonly requested", p: ["Requirements vary, but employers often ask for identity, education, and experience documents."],
          list: ["Passport copy with adequate validity", "Educational certificates where relevant", "Experience letters or references", "Professional licenses for regulated roles", "Medical or background checks when required"] },
        { h: "Red flags to avoid", p: ["Be careful with offers that pressure you to act quickly or bypass official channels."],
          list: ["Guaranteed visa without a real interview", "Payment requests to unknown individuals", "No written offer or company details", "Promises that sound too good to verify"] },
      ],
      conclusion: "Check official government sources and the employer's HR team before making travel or resignation decisions.",
    }),
    makeArticle({
      slug: "how-to-use-linkedin-and-gulf-job-portals",
      title: "LinkedIn and Gulf Job Portals: A Practical Plan",
      category: "Job Portals", date: "2026-06-20", author: "Gulf Jobs Desk",
      excerpt: "Use LinkedIn and Gulf job boards with a focused routine instead of sending random applications.",
      tags: ["linkedin", "job-portals", "applications"],
      data: { value: "30 min", label: "daily focused search beats random bulk applying" },
      lead: "Many Gulf openings are advertised online, but successful candidates treat job portals like a system, not a lottery. The goal is to find relevant roles, apply early, and follow up professionally.",
      takeaway: "Quality matters more than volume. A tailored application to the right opening is stronger than 100 generic submissions.",
      sections: [
        { h: "Set up your profile first", p: ["Before applying, make sure your online profile supports your CV."],
          list: ["Use a clear headline with role and industry", "Add country or relocation preference", "List skills that match Gulf vacancies", "Keep work dates consistent with your CV"] },
        { h: "Build a repeatable search routine", p: ["Use saved searches and alerts for target countries and role titles."],
          list: ["Search by role, not only by country", "Apply to recent posts first", "Track applications in a simple sheet", "Send polite follow-ups when appropriate"] },
      ],
      conclusion: "A calm daily routine will outperform rushed applications made only when desperation rises.",
    }),
    makeArticle({
      slug: "walk-in-interviews-in-dubai-doha-riyadh",
      title: "Walk-In Interviews in the Gulf: How to Prepare",
      category: "Interviews", date: "2026-06-14", author: "Gulf Jobs Desk",
      excerpt: "Prepare for walk-in interviews in Gulf cities with documents, timing, presentation, and follow-up basics.",
      tags: ["walk-in-interviews", "dubai", "gulf"],
      lead: "Walk-in interviews can move quickly, especially for hospitality, retail, sales, logistics, and support roles. Preparation helps you look professional even when the process is busy.",
      takeaway: "Treat a walk-in interview like a formal interview: verify the company, carry documents, dress appropriately, and answer clearly.",
      sections: [
        { h: "What to carry", p: ["Keep a simple folder ready so you are not searching for documents at the venue."],
          list: ["Printed CV copies", "Passport or ID copy when appropriate", "Certificates or licenses for the role", "Pen, notepad, and interview details", "A short list of references if requested"] },
        { h: "How to protect yourself", p: ["Verify the company name, location, and job details before attending. Avoid anyone asking for fees to secure an interview."],
          list: ["Check the official company website", "Confirm the location on maps", "Do not hand over original documents casually", "Ask for written offer details before accepting"] },
      ],
      conclusion: "Good preparation helps you stand out while also avoiding risky or unclear opportunities.",
    }),
    makeArticle({
      slug: "recruitment-agencies-and-salary-expectations",
      title: "Recruitment Agencies and Salary Expectations",
      category: "Recruitment", date: "2026-06-08", author: "Gulf Jobs Desk",
      excerpt: "Work with Gulf recruiters professionally and discuss salary expectations without relying on invented numbers.",
      tags: ["recruiters", "salary", "agencies"],
      lead: "Recruitment agencies can help connect candidates with employers, but they are not a shortcut around preparation. Your CV, communication, and realistic expectations still matter.",
      takeaway: "Use salary discussions to show you understand the role, benefits, experience level, and local market, not to demand unsupported figures.",
      sections: [
        { h: "How to work with recruiters", p: ["Be clear, responsive, and consistent with your information."],
          list: ["Send a focused CV, not every version you have", "Mention target countries and role types", "Reply professionally and quickly", "Keep records of where your CV is submitted"] },
        { h: "Discussing salary safely", p: ["Compensation varies by country, industry, company size, benefits, and experience. Avoid quoting numbers you cannot support."],
          list: ["Ask for the full package structure", "Consider housing, transport, medical insurance, and flights", "Research current listings for similar roles", "Be honest about your minimum acceptable range"] },
      ],
      conclusion: "The best recruiter relationships are built on accurate information, realistic expectations, and professional follow-up.",
    }),
  ],
};
