// Per-site identity + seed content. The ONLY file that differs between sites.
import { makeArticle } from "./lib/seed";

export const SITE = {
  name: "Gulf Jobs Guide",
  lead: "Plan your next",
  accent: "Gulf Career Move",
  tagline: "Professional Gulf job guides, CV templates, and safer application tips for UAE, Saudi Arabia, Oman, Qatar, Kuwait, and Bahrain.",
  eyebrow: "Gulf careers · CV maker · Job search guides",
  nav: ["CV", "Visas", "Interviews", "Job Portals", "Recruitment"],
  defaultTheme: "royal",
  domain: "gulfjobss.com",

  seedArticles: [
    makeArticle({
      slug: "how-to-apply-for-jobs-in-uae",
      title: "How to Apply for Jobs in the UAE",
      category: "Job Portals", date: "2026-06-30", author: "Gulf Jobs Desk",
      excerpt: "A practical UAE job search guide covering CVs, job portals, recruiters, interviews, offer checks, and red flags to avoid.",
      tags: ["uae jobs", "dubai jobs", "job search", "mohre", "cv"],
      data: { value: "60-120 days", label: "common UAE job exploration permit durations, depending on eligibility and official rules" },
      lead: "The UAE job market is active, competitive, and full of opportunity, but successful applicants do not rely on random messages or miracle offers. They prepare a targeted CV, apply through trusted channels, verify every employer, and treat the process like a daily routine.",
      takeaway: "The safest UAE job search is built on three habits: apply through reliable channels, verify the offer through official sources, and never pay for a guaranteed job or visa shortcut.",
      sections: [
        { h: "Start with a UAE-ready CV", p: ["Before applying anywhere, prepare a CV that matches UAE recruiter expectations. Keep it direct, keyword-friendly, and easy to scan on a phone or laptop."],
          list: ["Use a clear job title at the top, such as Sales Executive, Accountant, Driver, Nurse, Technician, or Customer Service Agent", "Mention your current location, target emirate, notice period, visa status, and availability", "Add measurable experience instead of generic duties", "Keep skills close to the jobs you actually want", "Save your CV as PDF with a professional file name"] },
        { h: "Search through reliable UAE job channels", p: ["The official UAE government jobs guidance says job seekers can use job portals, online job fairs, classifieds, recruitment agencies, company websites, and professional networking websites. Use more than one channel, but keep your applications focused."],
          list: ["Create strong profiles on major job portals and keep them updated", "Use LinkedIn daily and search by job title plus UAE city, such as Dubai, Abu Dhabi, Sharjah, Ajman, or Ras Al Khaimah", "Apply directly on company career pages for banks, hotels, hospitals, logistics companies, construction firms, schools, and retailers", "Follow licensed recruitment agencies, but do not pay unofficial fees for job promises", "Track every application in a simple spreadsheet with company name, role, date, source, and follow-up status"] },
        { h: "Apply with a focused daily routine", p: ["A strong UAE job search is not about sending hundreds of weak applications. It is about sending the right applications quickly and consistently."],
          list: ["Shortlist 10-15 relevant jobs daily", "Adjust your CV headline and first skills section for each role type", "Write a short message that matches the job requirements", "Apply early when a role is newly posted", "Follow up politely after a few working days if the company details are clear"] },
        { h: "Be careful with visas and work permission", p: ["Do not work in the UAE on a tourist or visit visa without the correct legal work status. If you are entering the country to search for work, check official UAE sources for the current job exploration entry permit rules, eligibility, duration, fees, and documents before making plans."],
          list: ["Use official government portals for current visa information", "Do not trust anyone promising a guaranteed work visa without a real employer and process", "Keep copies of your passport, certificates, experience letters, and professional licenses ready", "Never hand over original documents casually", "Confirm every step before resigning from your current job or booking travel"] },
        { h: "Verify the job offer before you accept", p: ["For mainland private sector jobs, the Ministry of Human Resources and Emiratisation (MOHRE) is the key official authority. A serious offer should have proper company details and should be verifiable through official channels where applicable."],
          list: ["Check the employer's website, trade license details, office location, and online presence", "Ask for a written offer with salary, benefits, job title, work location, and contract period", "Look for official offer details such as transaction or company numbers where required", "Compare the offer details with what was discussed in the interview", "Contact official channels or the UAE embassy/consulate if an overseas offer feels suspicious"] },
        { h: "Red flags every UAE job seeker must avoid", p: ["Scams often target people who are desperate to move quickly. Slow down when the offer sounds too easy, too urgent, or too expensive."],
          list: ["Someone asks you to pay for a guaranteed job", "The company has no real website, office address, or trade license information", "The salary is unrealistically high for your experience", "They refuse to provide a written offer", "They ask for passport originals before a proper process", "They pressure you to travel immediately without verified documents"] },
      ],
      conclusion: "The best way to apply for jobs in the UAE is to stay professional, organized, and careful. Build a strong CV, apply through trusted channels, verify every offer, and avoid shortcuts. A slower but verified process is always better than a fast promise that puts your money, documents, or legal status at risk.",
    }),
    makeArticle({
      slug: "best-way-to-search-jobs-in-dubai",
      title: "Best Way to Search Jobs in Dubai",
      category: "Job Portals", date: "2026-06-29", author: "Gulf Jobs Desk",
      excerpt: "A practical Dubai job search plan for portals, LinkedIn, company websites, walk-ins, and recruiter follow-ups.",
      tags: ["dubai jobs", "uae jobs", "job portals", "linkedin"],
      lead: "Dubai has thousands of vacancies across hospitality, retail, logistics, construction, healthcare, finance, real estate, and office support, but the market moves fast. The best candidates do not wait for one portal to work; they build a daily system.",
      takeaway: "For Dubai jobs, combine portals, LinkedIn, direct company applications, and verified recruiter contact. Random mass applying is weaker than a focused daily routine.",
      sections: [
        { h: "Use job portals with specific searches", p: ["Search by role title first, then filter by Dubai or nearby emirates. A narrow search brings better matches than typing only 'Dubai jobs'."],
          list: ["Use exact job titles such as Accountant, Driver, Receptionist, Sales Executive, Waiter, Technician, Nurse, or Storekeeper", "Save searches and turn on alerts", "Apply to fresh postings first", "Update your profile every few days so recruiters see recent activity"] },
        { h: "Search LinkedIn like a recruiter", p: ["LinkedIn works best when your profile headline and CV match the roles you apply for."],
          list: ["Add Dubai, UAE, or open to relocation in your profile", "Follow target companies and recruiters", "Comment professionally on hiring posts", "Send short messages with your role, experience, and availability"] },
        { h: "Do not ignore company career pages", p: ["Large employers often post vacancies on their own websites before or alongside job portals."],
          list: ["Check hotels, hospitals, supermarkets, banks, delivery companies, schools, and facility management firms", "Apply directly when the role is active", "Keep a record of the application date and job ID"] },
        { h: "Follow up without annoying employers", p: ["A polite follow-up can help, but repeated messages can hurt your chances."],
          list: ["Wait a few working days before following up", "Mention the exact role you applied for", "Keep the message under five lines", "Do not send your CV again and again in unrelated chats"] },
      ],
      conclusion: "Dubai job search success comes from consistency, not panic. Apply daily, stay organized, avoid fake offers, and keep improving your CV until interviews start coming.",
    }),
    makeArticle({
      slug: "saudi-arabia-jobs-guide-for-foreign-workers",
      title: "Saudi Arabia Jobs Guide for Foreign Workers",
      category: "Job Portals", date: "2026-06-28", author: "Gulf Jobs Desk",
      excerpt: "How foreign workers can prepare for Saudi jobs with the right CV, employer checks, documents, and interview strategy.",
      tags: ["saudi jobs", "riyadh jobs", "jeddah jobs", "foreign workers"],
      lead: "Saudi Arabia is hiring across construction, hospitality, oil and gas, healthcare, logistics, retail, education, and professional services. For foreign workers, preparation matters because employers need clear documents, relevant experience, and realistic salary expectations.",
      takeaway: "The strongest Saudi job applications show role-specific experience, document readiness, and respect for the official employer-led process.",
      sections: [
        { h: "Choose the right target city and sector", p: ["Riyadh, Jeddah, Dammam, Khobar, Makkah, Madinah, and project zones can have very different hiring needs."],
          list: ["Riyadh has many corporate, government-linked, technology, sales, and admin roles", "Jeddah has hospitality, logistics, retail, and trading opportunities", "Eastern Province often has oil, gas, industrial, engineering, and technical roles"] },
        { h: "Prepare documents before interviews", p: ["Employers may ask for documents quickly once they shortlist you. Keep scans ready and readable."],
          list: ["Passport copy", "Education certificates", "Experience letters", "Professional licenses where required", "Updated CV and passport-size photo"] },
        { h: "Make your CV Saudi-relevant", p: ["A general CV is easy to ignore. Show experience that matches the exact industry and job title."],
          list: ["Mention GCC or Middle East experience if you have it", "Highlight safety, compliance, customer service, technical tools, or team leadership where relevant", "Add language skills honestly", "Keep salary expectations realistic and flexible"] },
        { h: "Check offer quality before resigning", p: ["Do not make life decisions based only on a WhatsApp promise."],
          list: ["Ask for written offer details", "Confirm salary, accommodation, transport, medical insurance, and leave terms", "Verify employer identity and recruiter authority", "Avoid payments to unofficial middlemen"] },
      ],
      conclusion: "Saudi jobs can be excellent for prepared candidates. Target the right sector, keep documents ready, apply through trusted routes, and verify every offer before taking action.",
    }),
    makeArticle({
      slug: "oman-jobs-for-expats-how-to-apply",
      title: "Oman Jobs for Expats: How to Apply",
      category: "Job Portals", date: "2026-06-27", author: "Gulf Jobs Desk",
      excerpt: "A clear guide for expats applying to jobs in Oman, including CV focus, industries, documents, and safe offer checks.",
      tags: ["oman jobs", "muscat jobs", "expat jobs", "gulf jobs"],
      lead: "Oman offers opportunities in hospitality, oil and gas, logistics, education, healthcare, construction, sales, and technical services. The market is smaller than Dubai or Riyadh, so quality applications matter even more.",
      takeaway: "For Oman jobs, apply with a focused CV and patience. A smaller market rewards candidates who match the role closely and communicate professionally.",
      sections: [
        { h: "Target realistic industries", p: ["Start with sectors where your experience clearly fits. Oman employers often prefer candidates who can show stable experience and practical skills."],
          list: ["Hospitality and tourism", "Oil, gas, and industrial services", "Healthcare and clinics", "Logistics and transport", "Education and training", "Retail and sales"] },
        { h: "Make your CV simple and direct", p: ["Recruiters should quickly understand your job title, years of experience, current country, and availability."],
          list: ["Use a clean one or two-page CV", "Mention tools, machines, systems, or certifications", "Add GCC experience if relevant", "Avoid long paragraphs and unrelated personal details"] },
        { h: "Use multiple application routes", p: ["Because the market is smaller, do not depend on one job board."],
          list: ["Apply on company websites", "Use LinkedIn search alerts for Muscat and Oman", "Contact licensed recruitment agencies", "Network with professionals already working in your target sector"] },
        { h: "Stay careful with offers", p: ["A real employer should be able to explain the role, package, location, and joining process clearly."],
          list: ["Do not pay for guaranteed job promises", "Ask for written details", "Verify company website and office information", "Be careful if the offer is rushed or vague"] },
      ],
      conclusion: "Oman job search takes patience and focus. Apply to roles that match your profile, keep documents ready, and verify the employer before accepting any offer.",
    }),
    makeArticle({
      slug: "qatar-jobs-application-guide",
      title: "Qatar Jobs Application Guide",
      category: "Interviews", date: "2026-06-26", author: "Gulf Jobs Desk",
      excerpt: "How to apply for Qatar jobs with a better CV, targeted searches, interview preparation, and safe employer checks.",
      tags: ["qatar jobs", "doha jobs", "interviews", "cv"],
      lead: "Qatar attracts job seekers in hospitality, aviation, construction, engineering, healthcare, education, retail, security, and office support. Competition can be strong, so your application needs to be targeted and professional.",
      takeaway: "Qatar employers respond better to candidates who show exact role fit, clear availability, and professional communication from the first message.",
      sections: [
        { h: "Build your Qatar job target list", p: ["Do not apply to every vacancy. Choose role types where your experience gives you a real chance."],
          list: ["List 3-5 target job titles", "Choose sectors that match your background", "Track companies hiring in Doha and other areas", "Keep notes on requirements you see repeatedly"] },
        { h: "Improve your CV before applying", p: ["A Qatar-focused CV should be clear, honest, and relevant."],
          list: ["Add your current location and willingness to relocate", "Mention visa status if already in Qatar", "Highlight certifications and licenses", "Show measurable achievements where possible"] },
        { h: "Prepare for screening calls", p: ["Many candidates lose opportunities because they are not ready when recruiters call."],
          list: ["Keep your phone active", "Practice a 30-second introduction", "Know your expected salary range", "Be ready to explain notice period and availability"] },
        { h: "Verify before accepting", p: ["A serious offer should include the employer name, job title, salary, benefits, location, and joining process."],
          list: ["Check the company website and online presence", "Avoid paying unofficial fees", "Ask questions about accommodation, transport, medical insurance, and leave", "Do not resign until the process is clear"] },
      ],
      conclusion: "Qatar job search works best when you are prepared before the call comes. Keep your CV strong, apply with focus, and verify details before making commitments.",
    }),
    makeArticle({
      slug: "kuwait-jobs-guide-for-new-applicants",
      title: "Kuwait Jobs Guide for New Applicants",
      category: "Job Portals", date: "2026-06-25", author: "Gulf Jobs Desk",
      excerpt: "A practical Kuwait job search guide covering CVs, target sectors, recruiter communication, and offer safety.",
      tags: ["kuwait jobs", "gulf jobs", "job search", "recruiters"],
      lead: "Kuwait has opportunities in retail, healthcare, oil services, logistics, education, hospitality, construction, and office roles. New applicants should focus on matching their experience to the vacancy and avoiding unclear offers.",
      takeaway: "A strong Kuwait application is simple: relevant CV, trusted application source, clear communication, and careful offer verification.",
      sections: [
        { h: "Pick roles that fit your background", p: ["The fastest way to waste time is applying to jobs where your experience does not match basic requirements."],
          list: ["Search by exact job title", "Check required years of experience", "Notice language, license, and certification requirements", "Avoid applying if the role is clearly outside your skill set"] },
        { h: "Keep your CV practical", p: ["Recruiters need to understand your work history quickly."],
          list: ["Use reverse chronological experience", "Add duties that match the job description", "Mention equipment, software, or customer types", "Keep references available but not necessarily on the CV"] },
        { h: "Communicate professionally", p: ["Your message can affect whether a recruiter opens your CV."],
          list: ["Write a short subject line", "Mention the role name", "State years of experience and current location", "Avoid sending repeated voice notes or unclear messages"] },
        { h: "Watch for red flags", p: ["Be careful when the process is unclear or money is requested too early."],
          list: ["No company name", "No written role details", "Pressure to pay immediately", "Unrealistic salary", "No interview or skill discussion"] },
      ],
      conclusion: "Kuwait jobs are easier to approach when your CV, target roles, and follow-up system are organized. Stay patient and verify everything before accepting.",
    }),
    makeArticle({
      slug: "bahrain-jobs-how-to-stand-out",
      title: "Bahrain Jobs: How to Stand Out",
      category: "CV", date: "2026-06-24", author: "Gulf Jobs Desk",
      excerpt: "How applicants can improve their Bahrain job search with a focused CV, local market targeting, and better interview preparation.",
      tags: ["bahrain jobs", "manama jobs", "cv tips", "interviews"],
      lead: "Bahrain's job market is compact, which means reputation, fit, and communication matter. Whether you target Manama roles or wider Bahrain opportunities, your CV should make your value clear quickly.",
      takeaway: "To stand out in Bahrain, apply with a focused CV, show practical skills, and communicate like someone who understands the role.",
      sections: [
        { h: "Focus on fit, not volume", p: ["Because the market is smaller, sending the same CV everywhere is less effective."],
          list: ["Choose roles that match your strongest experience", "Customize your CV summary for each role type", "Mention tools, systems, or customer segments", "Use clear dates and job titles"] },
        { h: "Strengthen your professional profile", p: ["Recruiters may check your online presence before responding."],
          list: ["Update LinkedIn headline and location preference", "Add a professional photo if appropriate", "Keep job history consistent with your CV", "Remove confusing or outdated information"] },
        { h: "Prepare for practical interview questions", p: ["Employers often want to know how you handled real work situations."],
          list: ["Prepare examples of solving customer issues", "Explain how you work under pressure", "Know your previous targets, tools, or responsibilities", "Be clear about salary expectations and availability"] },
        { h: "Protect yourself from weak offers", p: ["Small markets can still have scams or unclear promises."],
          list: ["Verify company identity", "Ask for written offer terms", "Do not hand over original documents without a proper process", "Avoid paying for guaranteed employment"] },
      ],
      conclusion: "Bahrain job search rewards clarity and professionalism. A focused CV and careful follow-up can help you stand out more than mass applications.",
    }),
    makeArticle({
      slug: "linkedin-profile-for-gulf-jobs",
      title: "LinkedIn Profile for Gulf Jobs",
      category: "Job Portals", date: "2026-06-23", author: "Gulf Jobs Desk",
      excerpt: "Step-by-step LinkedIn profile tips for Gulf job seekers who want more recruiter views and better application results.",
      tags: ["linkedin", "gulf jobs", "profile", "recruiters"],
      lead: "LinkedIn can help Gulf job seekers, but only when the profile clearly matches the roles they want. A blank profile with a generic headline will not compete with candidates who show skills, location, and experience clearly.",
      takeaway: "Your LinkedIn profile should make a recruiter understand your target job, experience level, location preference, and key skills in under ten seconds.",
      sections: [
        { h: "Fix your headline first", p: ["Your headline appears in search results and messages, so make it specific."],
          list: ["Use your target job title", "Add your strongest industry or skill", "Mention GCC or UAE experience if relevant", "Avoid phrases like looking for any job"] },
        { h: "Write a strong About section", p: ["The About section should sound professional and direct, not desperate."],
          list: ["Start with your role and years of experience", "Mention industries you know", "Add key tools or responsibilities", "Close with target roles and preferred Gulf countries"] },
        { h: "Use keywords recruiters search for", p: ["Recruiters search by titles, skills, certifications, and locations."],
          list: ["Add job titles used in vacancies", "Include software and technical skills", "Mention languages honestly", "Add certifications and licenses"] },
        { h: "Message recruiters correctly", p: ["A good message is short and relevant."],
          list: ["Greet politely", "Mention the exact role or industry", "Summarize experience in one line", "Attach or offer your CV", "Do not send repeated messages every day"] },
      ],
      conclusion: "A polished LinkedIn profile will not guarantee a job, but it can increase recruiter trust and make your applications stronger across the Gulf.",
    }),
    makeArticle({
      slug: "gulf-recruitment-agencies-safe-guide",
      title: "Gulf Recruitment Agencies: Safe Guide",
      category: "Recruitment", date: "2026-06-22", author: "Gulf Jobs Desk",
      excerpt: "How to work with Gulf recruitment agencies safely, professionally, and without falling for fake job promises.",
      tags: ["recruitment agencies", "gulf recruiters", "job scams", "offers"],
      lead: "Recruitment agencies can connect candidates with real employers, but not every person claiming to be an agent is trustworthy. Job seekers need to understand how agencies work and where the risks are.",
      takeaway: "A genuine recruiter explains the role, employer, process, and requirements clearly. A risky agent pressures you for money, documents, or fast decisions without proof.",
      sections: [
        { h: "What a good recruiter does", p: ["A professional recruiter screens candidates for employer vacancies. They should care about role fit, experience, and communication."],
          list: ["Shares job title and basic requirements", "Explains interview process", "Requests a relevant CV", "Communicates from a professional email or verified channel", "Does not promise guaranteed selection"] },
        { h: "How to approach agencies", p: ["Make it easy for recruiters to understand your profile."],
          list: ["Send one clean CV", "Mention target roles and countries", "State current location and availability", "Keep messages short", "Reply quickly when they ask for information"] },
        { h: "Warning signs", p: ["Scam agents often focus on payment before interviews or documents before details."],
          list: ["Guaranteed job without interview", "Large upfront payment", "No company name", "No written job description", "Pressure to send passport originals", "Refusal to answer basic questions"] },
        { h: "Keep your own records", p: ["Tracking protects you from confusion and duplicate submissions."],
          list: ["Record agency name and contact person", "Note where your CV was submitted", "Save offer letters and messages", "Compare salary and benefits before accepting"] },
      ],
      conclusion: "Recruitment agencies can help, but they are not magic. Use them professionally, verify every opportunity, and never let urgency push you into unsafe decisions.",
    }),
    makeArticle({
      slug: "walk-in-interview-documents-for-gulf-jobs",
      title: "Walk-In Interview Documents for Gulf Jobs",
      category: "Interviews", date: "2026-06-21", author: "Gulf Jobs Desk",
      excerpt: "A practical document checklist and preparation guide for Gulf walk-in interviews in retail, hospitality, logistics, and support roles.",
      tags: ["walk-in interview", "documents", "gulf jobs", "interview tips"],
      lead: "Walk-in interviews can be useful for roles in hospitality, retail, logistics, sales, security, facility management, and customer support. They can also be crowded and fast, so preparation matters.",
      takeaway: "A walk-in interview is still a formal interview. Carry organized documents, dress properly, verify the employer, and never hand over originals casually.",
      sections: [
        { h: "Documents to carry", p: ["Keep your documents in a clean folder so you can present them quickly."],
          list: ["Printed CV copies", "Passport or ID copy when appropriate", "Visa copy if already in the country", "Education certificates", "Experience letters", "Professional licenses or driving license if relevant", "Passport-size photos if requested"] },
        { h: "What to prepare before going", p: ["Do not attend blindly just because a poster says walk-in interview."],
          list: ["Check company name and location", "Confirm date and timing", "Read job requirements", "Prepare a short self-introduction", "Plan transport and arrive early"] },
        { h: "How to answer quickly", p: ["Walk-in interviews are often short. Your answers should be clear."],
          list: ["State your role and years of experience", "Mention relevant skills", "Explain availability and visa status honestly", "Give one example of past work success"] },
        { h: "Safety checks", p: ["Crowded hiring events can attract fake agents too."],
          list: ["Do not pay for interview access", "Do not leave original passport or certificates", "Ask for written offer details", "Verify company before accepting"] },
      ],
      conclusion: "Walk-in interviews can work when you are prepared. Treat them seriously, stay organized, and protect your documents.",
    }),
    makeArticle({
      slug: "gulf-job-offer-red-flags",
      title: "Gulf Job Offer Red Flags",
      category: "Visas", date: "2026-06-20", author: "Gulf Jobs Desk",
      excerpt: "The most important warning signs to check before accepting a Gulf job offer or sharing documents.",
      tags: ["job offer", "red flags", "visa scams", "gulf jobs"],
      lead: "A Gulf job offer can change your life, but a fake offer can cost money, documents, and time. Every job seeker should know the warning signs before accepting anything.",
      takeaway: "If an offer is vague, rushed, expensive, or impossible to verify, stop and check before moving forward.",
      sections: [
        { h: "Money requests before proof", p: ["Some legitimate processes have official fees, but fake agents often demand money before giving real employer details."],
          list: ["Payment for guaranteed job", "Payment to unknown personal accounts", "Extra charges that keep changing", "No receipt or company invoice"] },
        { h: "Weak employer information", p: ["A real employer should have a traceable identity."],
          list: ["No website or office address", "No trade license or registration details", "Email from a free personal account only", "Company name does not match documents"] },
        { h: "Unrealistic salary or benefits", p: ["Scammers use high salary promises to make candidates ignore common sense."],
          list: ["Salary far above market for your role", "No interview or skill test", "Benefits that sound too perfect", "Immediate selection without discussion"] },
        { h: "Document pressure", p: ["Your documents are valuable. Treat them carefully."],
          list: ["Request for original passport early", "Pressure to send certificates without employer proof", "No written privacy or process explanation", "Threats that the offer will disappear immediately"] },
      ],
      conclusion: "Good opportunities can wait for verification. Before accepting any Gulf job offer, confirm the employer, written terms, official process, and your own legal status.",
    }),
    makeArticle({
      slug: "salary-expectations-for-gulf-job-interviews",
      title: "Salary Expectations for Gulf Interviews",
      category: "Interviews", date: "2026-06-19", author: "Gulf Jobs Desk",
      excerpt: "How to discuss salary expectations in Gulf job interviews without sounding unprepared or unrealistic.",
      tags: ["salary expectations", "interview", "gulf jobs", "benefits"],
      lead: "Salary questions are common in Gulf interviews, and many candidates answer too quickly. A better answer shows that you understand the role, total package, and market differences between countries and industries.",
      takeaway: "Do not discuss only basic salary. Ask about the full package: housing, transport, medical insurance, flights, commission, overtime, and leave.",
      sections: [
        { h: "Research before the interview", p: ["You do not need perfect salary data, but you should know the rough market for your role."],
          list: ["Check current job postings", "Compare similar roles by country and city", "Ask trusted professionals in your industry", "Consider your years of experience and certifications"] },
        { h: "Understand full package", p: ["In Gulf jobs, the total package can matter more than the headline salary."],
          list: ["Basic salary", "Accommodation or housing allowance", "Transport allowance", "Medical insurance", "Annual ticket or leave travel", "Commission or overtime policy"] },
        { h: "Give a flexible but clear answer", p: ["Avoid saying 'anything is okay' because it can make you look unprepared."],
          list: ["Mention that you are open based on the full package", "Give a reasonable range if asked", "Link your expectation to experience and responsibilities", "Stay polite and professional"] },
        { h: "Know your minimum before negotiating", p: ["Before accepting, calculate real living costs and family obligations."],
          list: ["Rent or accommodation", "Food and transport", "Debt or family support", "Visa or relocation costs", "Savings target"] },
      ],
      conclusion: "Salary discussion is not only about asking for more. It is about understanding the complete offer and making a decision that is financially safe.",
    }),
    makeArticle({
      slug: "gulf-cv-format-for-uae-saudi-qatar-jobs",
      title: "Gulf CV Format: What Recruiters Expect",
      category: "CV", date: "2026-06-29", author: "Gulf Jobs Desk",
      excerpt: "Build a clear, recruiter-friendly CV for UAE, Saudi, Qatar, Oman, Kuwait, and Bahrain applications.",
      tags: ["cv", "resume", "gulf-jobs"],
      lead: "A Gulf job search usually starts with a fast CV screening. Recruiters need to understand your role, industry, visa status, location, and key skills in seconds.",
      takeaway: "A strong Gulf CV is direct, keyword-friendly, and honest about experience, availability, and visa status.",
      sections: [
        { h: "What to include first", p: ["Put the details recruiters use to shortlist near the top."],
          list: ["Current location and target Gulf country", "Mobile number with country code", "Email and LinkedIn URL", "Notice period or availability", "Relevant certifications and languages"] },
        { h: "Make your experience easy to scan", p: ["Use role titles, company names, dates, and measurable responsibilities. Avoid generic lines that could describe any job."],
          list: ["Start bullets with action verbs", "Mention tools, systems, or equipment", "Match keywords from the job description", "Keep claims accurate and verifiable"] },
      ],
      conclusion: "Tailor one clean CV for each role type, then update it before every serious application.",
    }),
    makeArticle({
      slug: "work-visa-basics-for-gulf-job-seekers",
      title: "Work Visa Basics for Gulf Job Seekers",
      category: "Visas", date: "2026-06-25", author: "Gulf Jobs Desk",
      excerpt: "Understand the safe basics of employer sponsorship, offer letters, and documents before accepting a Gulf role.",
      tags: ["visas", "offers", "gulf"],
      lead: "Visa rules differ across the UAE, Saudi Arabia, Oman, Qatar, Kuwait, and Bahrain, but one principle stays the same: legitimate employment should follow official procedures.",
      takeaway: "Never pay for guaranteed-job promises or shortcuts. Verify the employer, offer, and process before sharing money or documents.",
      sections: [
        { h: "Documents commonly requested", p: ["Requirements vary, but employers often ask for identity, education, and experience documents."],
          list: ["Passport copy with adequate validity", "Educational certificates where relevant", "Experience letters or references", "Professional licenses for regulated roles", "Medical or background checks when required"] },
        { h: "Red flags to avoid", p: ["Be careful with offers that pressure you to act quickly or bypass official channels."],
          list: ["Guaranteed visa without a real interview", "Payment requests to unknown individuals", "No written offer or company details", "Promises that sound too good to verify"] },
      ],
      conclusion: "Check official government sources and the employer's HR team before making travel or resignation decisions.",
    }),
    makeArticle({
      slug: "how-to-use-linkedin-and-gulf-job-portals",
      title: "How to Use LinkedIn and Gulf Job Portals",
      category: "Job Portals", date: "2026-06-20", author: "Gulf Jobs Desk",
      excerpt: "Learn a practical daily routine for LinkedIn, Gulf job portals, recruiter follow-ups, CV targeting, and safer applications.",
      tags: ["linkedin", "gulf job portals", "bayt", "gulftalent", "applications"],
      data: { value: "30 min", label: "daily focused search beats random bulk applying" },
      lead: "LinkedIn and Gulf job portals can bring real interviews, but only when you use them with a clear system. Most job seekers fail because they create a weak profile, upload one generic CV, apply to every role, and then wait. A better approach is to define your target job, improve your profile, apply to fresh vacancies, and track follow-ups every day.",
      takeaway: "The winning routine is simple: optimize your profile once, search with specific job titles daily, tailor your CV for each role type, and follow up only when the company and vacancy are clear.",
      sections: [
        { h: "How should you set up your LinkedIn profile for Gulf jobs?", p: ["Your LinkedIn profile should answer the recruiter's first questions quickly: what role do you want, how much experience do you have, where are you available, and what skills make you relevant? Use a headline that includes your target role and industry instead of a generic line like 'looking for job'. For example, 'Sales Executive | 4+ Years Retail & B2B | Open to UAE and Saudi Roles' is much stronger than 'Need job urgently'. Keep your work dates, job titles, and skills consistent with your CV because recruiters often compare both before contacting you."],
          list: ["Use a professional photo and clear headline", "Add target countries such as UAE, Saudi Arabia, Qatar, Oman, Kuwait, or Bahrain", "Write a short About section with role, years of experience, industries, and strongest skills", "Add certificates, licenses, languages, tools, and systems recruiters search for", "Keep job history consistent with your CV and avoid exaggeration"] },
        { h: "Which Gulf job portals should you use with LinkedIn?", p: ["Do not depend on one website. LinkedIn is useful for recruiters, multinational companies, and direct networking, but regional portals can still be strong for Gulf vacancies. Use a mix of global and Gulf-focused platforms, then compare which one gives replies in your field. For job seekers targeting UAE roles, start with the full guide on <a href=\"/article/how-to-apply-for-jobs-in-uae\">how to apply for jobs in the UAE</a>. For Dubai-specific searching, also read the <a href=\"/article/best-way-to-search-jobs-in-dubai\">Dubai job search plan</a>."],
          list: ["LinkedIn for recruiter discovery, networking, and company posts", "Bayt-style portals for regional listings and profile visibility", "GulfTalent-style platforms for professional and specialist roles", "Company career pages for direct applications", "Government or official employer portals for public-sector and regulated roles"] },
        { h: "How do you search without wasting applications?", p: ["A focused search starts with role titles, not country names alone. Searching only 'UAE jobs' or 'Gulf jobs' gives broad results and attracts low-quality listings. Instead, search exact titles such as Accountant, Driver, Storekeeper, Nurse, Sales Executive, Waiter, Civil Engineer, HR Assistant, Technician, or Customer Service Agent. Then filter by location, date posted, experience level, and industry. Apply to recent posts first because many Gulf recruiters shortlist quickly."],
          list: ["Create 3-5 target job titles", "Search each title with target country or city", "Filter for jobs posted in the last few days", "Read requirements before applying", "Skip roles that clearly do not match your experience"] },
        { h: "What should you change before applying?", p: ["Small changes can improve response rate. You do not need to rewrite your whole CV every time, but your headline, summary, and top skills should match the role type. If you apply for sales roles, sales achievements and customer handling should be visible early. If you apply for logistics roles, inventory, warehouse, dispatch, ERP, driving license, or fleet experience should be visible. Use the free <a href=\"/cv-maker\">Gulf CV Maker</a> if your current CV is not clean or recruiter-friendly."],
          list: ["Match your CV title to the vacancy", "Move relevant skills near the top", "Use keywords from the job description naturally", "Remove unrelated details that distract from the role", "Save a separate CV version for each role type"] },
        { h: "How should you contact recruiters?", p: ["Recruiter messages should be short, clear, and respectful. Do not send long emotional messages, repeated voice notes, or unrelated CVs. A strong message says who you are, what role you fit, your years of experience, your location or relocation preference, and that your CV is attached. If the recruiter posted a specific vacancy, mention that role name. After applying, wait a few working days before following up."],
          list: ["Mention the exact role or vacancy", "Summarize your experience in one sentence", "State current location and availability", "Attach one relevant CV", "Avoid daily repeated messages"] },
        { h: "What should you track every day?", p: ["Tracking is what turns random applying into a job search system. Keep a spreadsheet with company name, job title, country, application source, date applied, CV version, recruiter name, and follow-up date. After two weeks, review which job titles and portals are producing views, calls, or replies. If nothing is working, the problem may be your CV, target roles, salary expectation, or profile keywords."],
          list: ["Applications sent", "Replies and recruiter calls", "Interview dates", "Rejected or expired roles", "CV version used", "Follow-up status"] },
        { h: "What mistakes should Gulf job seekers avoid?", p: ["Many candidates reduce their chances by applying too broadly or trusting unclear offers. Do not pay for guaranteed interviews or guaranteed visas. Do not send original documents casually. Do not accept a job based only on a chat message. For visa and offer safety, read the <a href=\"/article/gulf-job-offer-red-flags\">Gulf job offer red flags guide</a> before sharing money or sensitive documents."],
          list: ["Using one generic CV for every role", "Applying to jobs outside your experience", "Ignoring company verification", "Paying unofficial agents", "Not tracking applications", "Giving up after a few days"] },
        { h: "A simple 30-minute daily routine", p: ["Use the same routine every day for at least four weeks before judging results. Spend 10 minutes checking LinkedIn and recruiter posts, 10 minutes applying to fresh portal vacancies, 5 minutes checking company career pages, and 5 minutes updating your tracker and sending polite follow-ups. This habit is more powerful than applying randomly for three hours once a week."],
          list: ["10 minutes: LinkedIn searches and recruiter posts", "10 minutes: Gulf portal applications", "5 minutes: company career pages", "5 minutes: tracker updates and follow-ups"] },
      ],
      conclusion: "LinkedIn and Gulf job portals work best when you use them as a system. Build a strong profile, search exact job titles, apply early, tailor your CV, track every application, and verify offers before making decisions. A focused 30-minute daily routine can outperform hundreds of rushed applications.",
    }),
    makeArticle({
      slug: "walk-in-interviews-in-dubai-doha-riyadh",
      title: "Walk-In Interviews in the Gulf: How to Prepare",
      category: "Interviews", date: "2026-06-14", author: "Gulf Jobs Desk",
      excerpt: "Prepare for walk-in interviews in Gulf cities with documents, timing, presentation, and follow-up basics.",
      tags: ["walk-in-interviews", "dubai", "gulf"],
      lead: "Walk-in interviews can move quickly, especially for hospitality, retail, sales, logistics, and support roles. Preparation helps you look professional even when the process is busy.",
      takeaway: "Treat a walk-in interview like a formal interview: verify the company, carry documents, dress appropriately, and answer clearly.",
      sections: [
        { h: "What to carry", p: ["Keep a simple folder ready so you are not searching for documents at the venue."],
          list: ["Printed CV copies", "Passport or ID copy when appropriate", "Certificates or licenses for the role", "Pen, notepad, and interview details", "A short list of references if requested"] },
        { h: "How to protect yourself", p: ["Verify the company name, location, and job details before attending. Avoid anyone asking for fees to secure an interview."],
          list: ["Check the official company website", "Confirm the location on maps", "Do not hand over original documents casually", "Ask for written offer details before accepting"] },
      ],
      conclusion: "Good preparation helps you stand out while also avoiding risky or unclear opportunities.",
    }),
    makeArticle({
      slug: "recruitment-agencies-and-salary-expectations",
      title: "Recruitment Agencies and Salary Expectations",
      category: "Recruitment", date: "2026-06-08", author: "Gulf Jobs Desk",
      excerpt: "Work with Gulf recruiters professionally and discuss salary expectations without relying on invented numbers.",
      tags: ["recruiters", "salary", "agencies"],
      lead: "Recruitment agencies can help connect candidates with employers, but they are not a shortcut around preparation. Your CV, communication, and realistic expectations still matter.",
      takeaway: "Use salary discussions to show you understand the role, benefits, experience level, and local market, not to demand unsupported figures.",
      sections: [
        { h: "How to work with recruiters", p: ["Be clear, responsive, and consistent with your information."],
          list: ["Send a focused CV, not every version you have", "Mention target countries and role types", "Reply professionally and quickly", "Keep records of where your CV is submitted"] },
        { h: "Discussing salary safely", p: ["Compensation varies by country, industry, company size, benefits, and experience. Avoid quoting numbers you cannot support."],
          list: ["Ask for the full package structure", "Consider housing, transport, medical insurance, and flights", "Research current listings for similar roles", "Be honest about your minimum acceptable range"] },
      ],
      conclusion: "The best recruiter relationships are built on accurate information, realistic expectations, and professional follow-up.",
    }),
  ],
};
