// Per-site identity + seed content. The ONLY file that differs between sites.
import { makeArticle, makeStory } from "./lib/seed";

const IMG = {
  cat: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&q=80",
  dog: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80",
  parrot: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&q=80",
  bird: "https://images.unsplash.com/photo-1444464666168-49d633b86797?w=800&q=80",
  rooster: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80",
  rabbit: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=800&q=80",
};

export const SITE = {
  name: "Pet Lovers Daily",
  lead: "Celebrate",
  accent: "Happy, Healthy Pets",
  tagline: "Vet-informed tips, colorful pet stories, and a community sharing love for dogs, cats, birds, and more.",
  eyebrow: "Pets · Stories · Community",
  defaultTheme: "sunset",
  domain: "petlovers.com",

  // Article categories (shown on /articles page)
  articleCategories: [
    "Pet Health", "Pet Food & Care", "Medicine", "Pet House", "Dogs", "Cats", "Birds",
  ],

  // Hero banner — large professional pet images
  bannerPets: [
    { name: "Cat", emoji: "🐱", image: IMG.cat, color: "#fb7185" },
    { name: "Dog", emoji: "🐕", image: IMG.dog, color: "#f97316" },
    { name: "Parrot", emoji: "🦜", image: IMG.parrot, color: "#22c55e" },
    { name: "Bird", emoji: "🐦", image: IMG.bird, color: "#38bdf8" },
    { name: "Rooster", emoji: "🐓", image: IMG.rooster, color: "#f59e0b" },
    { name: "Rabbit", emoji: "🐰", image: IMG.rabbit, color: "#a855f7" },
  ],

  seedArticles: [
    makeArticle({
      slug: "reading-your-dogs-body-language",
      title: "Vet-Approved: How to Read Your Dog's Body Language",
      category: "Dogs", date: "2026-06-19", author: "Dr. Sara Lin",
      image: IMG.dog,
      excerpt: "Your dog is always talking. Learn the signals that prevent stress, bites, and miscommunication.",
      tags: ["dogs", "behavior", "training"],
      lead: "Dogs communicate constantly — just not in words. Learning their signals is the single best thing you can do for a calmer, safer household.",
      takeaway: "A wagging tail isn't always 'happy.' Read the whole body — ears, eyes, posture — not just one part.",
      sections: [
        { h: "Signs of a relaxed dog", p: ["A loose, wiggly body usually means your dog feels safe."],
          list: ["Soft eyes and a slightly open mouth", "Loose, sweeping tail wag", "Weight evenly balanced, ears neutral"] },
        { h: "Signs of stress", p: ["Catch these early to avoid escalation."],
          list: ["Lip licking, yawning when not tired", "Whale eye (whites showing)", "Tucked tail or frozen posture"] },
      ],
      conclusion: "When in doubt, give your dog space. Respecting their signals builds trust faster than any treat.",
    }),
    makeArticle({
      slug: "cat-nutrition-myths-that-wont-die",
      title: "Cat Nutrition Myths That Won't Die",
      category: "Pet Food & Care", date: "2026-06-16", author: "Dr. Omar Reyes",
      image: IMG.cat,
      excerpt: "Milk, vegetarian diets, and 'grain-free' — separating marketing from what cats actually need.",
      tags: ["cats", "nutrition", "diet"],
      lead: "Cats are obligate carnivores, yet the pet aisle is full of products that ignore that simple fact.",
      takeaway: "Cats need meat-based protein and plenty of water. Most 'trends' are for owners, not cats.",
      sections: [
        { h: "Three persistent myths", list: ["Cats need milk — most are lactose intolerant", "Cats can be vegetarian — they can't, safely", "'Grain-free' is automatically healthier — not necessarily"] },
        { h: "What actually matters", p: ["Prioritize animal protein, moisture, and portion control over buzzwords."] },
      ],
      conclusion: "Read the ingredient list, not the front of the bag — and ask your vet before any big diet change.",
    }),
    makeArticle({
      slug: "how-much-exercise-does-your-dog-need",
      title: "How Much Exercise Does Your Dog Really Need?",
      category: "Pet Health", date: "2026-06-11", author: "Dr. Sara Lin",
      image: IMG.dog,
      excerpt: "Breed, age, and energy level change the answer a lot. Here's a practical guide.",
      tags: ["dogs", "exercise", "health"],
      data: { value: "30–120 min", label: "daily activity, depending on breed and age" },
      lead: "A bored dog is a destructive dog. But 'enough exercise' looks very different for a bulldog than a border collie.",
      takeaway: "Match the activity to the dog. Mental work counts as much as physical for high-energy breeds.",
      sections: [
        { h: "Rough daily targets", list: ["Low-energy / brachycephalic: 30 min, gentle", "Most family dogs: 60 min mixed activity", "Working breeds: 90–120 min + training games"] },
        { h: "Don't forget the brain", p: ["Sniff walks, puzzle feeders, and training tire a dog out faster than a flat walk."] },
      ],
      conclusion: "Consistency beats intensity. A tired dog is a happy, well-behaved companion.",
    }),
    makeArticle({
      slug: "senior-pet-care-checklist",
      title: "Senior Pet Care: A Practical Checklist",
      category: "Pet Health", date: "2026-06-05", author: "Dr. Omar Reyes",
      image: IMG.cat,
      excerpt: "Older pets need small changes that make a big difference to comfort and lifespan.",
      tags: ["senior", "health", "care"],
      lead: "Pets age faster than we do, and the senior years arrive quietly.",
      takeaway: "Twice-yearly vet visits catch age-related issues while they're still easy to manage.",
      sections: [
        { h: "The senior checklist", list: ["Vet check-ups every 6 months", "Joint support and softer bedding", "Adjusted diet for slower metabolism", "Watch for changes in thirst, weight, or mobility"] },
      ],
      conclusion: "Aging isn't a disease. With small tweaks, your senior pet's best years can also be their most comfortable.",
    }),
    makeArticle({
      slug: "choosing-food-for-a-picky-cat",
      title: "Choosing the Right Food for a Picky Cat",
      category: "Pet Food & Care", date: "2026-05-28", author: "Dr. Omar Reyes",
      image: IMG.cat,
      excerpt: "Fussy eaters aren't being difficult on purpose. Here's how to win them over the healthy way.",
      tags: ["cats", "nutrition", "feeding"],
      lead: "If your cat turns up its nose at every bowl, you're not alone.",
      takeaway: "Change food gradually over 7–10 days. Sudden switches cause both refusal and upset stomachs.",
      sections: [
        { h: "Win over a picky eater", list: ["Warm wet food slightly to boost aroma", "Transition new food slowly, mixing in", "Keep feeding times consistent"] },
        { h: "When to worry", p: ["A cat that stops eating for more than 24 hours needs a vet — fasting is genuinely dangerous for cats."] },
      ],
      conclusion: "Patience and a steady routine beat constant switching.",
    }),
    makeArticle({
      slug: "essential-pet-medicine-cabinet",
      title: "What Every Pet Owner Should Keep in a Medicine Cabinet",
      category: "Medicine", date: "2026-05-20", author: "Dr. Sara Lin",
      image: IMG.dog,
      excerpt: "From wound care to flea prevention — the basics every home with pets should have ready.",
      tags: ["medicine", "first-aid", "health"],
      lead: "When your pet gets a minor scrape at 9 PM, having the right supplies on hand saves stress and vet trips.",
      takeaway: "Never give human painkillers to pets without vet guidance — many are toxic to dogs and cats.",
      sections: [
        { h: "Must-have items", list: ["Pet-safe antiseptic wipes", "Gauze and self-adhesive bandage", "Tick remover tool", "Electrolyte gel for dehydration", "Flea and tick preventive (vet-approved)"] },
      ],
      conclusion: "Keep your vet's emergency number on the fridge alongside these supplies.",
    }),
    makeArticle({
      slug: "designing-the-perfect-pet-house",
      title: "Designing the Perfect Indoor Pet House",
      category: "Pet House", date: "2026-05-14", author: "Dr. Omar Reyes",
      image: IMG.rabbit,
      excerpt: "Cozy corners, safe materials, and the right size — how to build a space your pet actually uses.",
      tags: ["pet-house", "home", "comfort"],
      lead: "A pet house isn't just decoration — it's a retreat where your companion feels secure.",
      takeaway: "Place the house in a quiet corner away from foot traffic but still within sight of the family.",
      sections: [
        { h: "Design principles", list: ["Size: pet should stand, turn, and stretch comfortably", "Washable bedding inside", "Non-toxic wood or plastic materials", "Good ventilation for summer months"] },
      ],
      conclusion: "The best pet house is one your pet chooses to enter on their own.",
    }),
    makeArticle({
      slug: "parrot-care-basics-for-beginners",
      title: "Parrot Care Basics for First-Time Bird Owners",
      category: "Birds", date: "2026-05-08", author: "Dr. Sara Lin",
      image: IMG.parrot,
      excerpt: "Colorful, intelligent, and demanding — what you need to know before bringing a parrot home.",
      tags: ["birds", "parrot", "care"],
      lead: "Parrots can live 50+ years and need daily social interaction, mental stimulation, and a varied diet.",
      takeaway: "A bored parrot becomes a loud, destructive parrot. Plan for enrichment every single day.",
      sections: [
        { h: "Daily essentials", list: ["Large cage with room to spread wings", "Fresh fruits, vegetables, and pellets", "2+ hours of out-of-cage time", "Toys rotated weekly to prevent boredom"] },
      ],
      conclusion: "Parrots reward patient owners with decades of companionship and personality.",
    }),
    makeArticle({
      slug: "rabbit-housing-and-diet-guide",
      title: "Rabbit Housing and Diet: A Complete Guide",
      category: "Pet House", date: "2026-04-30", author: "Dr. Omar Reyes",
      image: IMG.rabbit,
      excerpt: "Hay, space to hop, and hiding spots — the fundamentals of happy rabbit care.",
      tags: ["rabbit", "housing", "diet"],
      lead: "Rabbits are not low-maintenance cage pets. They need room to run and a hay-first diet.",
      takeaway: "Unlimited timothy hay should make up 80% of a rabbit's diet.",
      sections: [
        { h: "Housing needs", list: ["Minimum 4×2 ft enclosure plus daily free-roam time", "Hide box for security", "Litter box trained in a corner", "Chew toys to protect teeth"] },
      ],
      conclusion: "A well-cared-for rabbit is quiet, clean, and surprisingly affectionate.",
    }),
    makeArticle({
      slug: "common-cat-health-warning-signs",
      title: "10 Cat Health Warning Signs You Should Never Ignore",
      category: "Pet Health", date: "2026-04-22", author: "Dr. Sara Lin",
      image: IMG.cat,
      excerpt: "Cats hide illness well. These subtle changes mean it's time to call the vet.",
      tags: ["cats", "health", "warning-signs"],
      lead: "By the time a cat looks obviously sick, the problem may have been brewing for days.",
      takeaway: "Sudden hiding, appetite loss, or litter-box changes always deserve a vet check.",
      sections: [
        { h: "Watch for these", list: ["Not eating for 24+ hours", "Hiding more than usual", "Vomiting more than once a week", "Changes in litter box habits", "Labored breathing or open-mouth panting"] },
      ],
      conclusion: "Early vet visits cost less and save lives. Trust your instincts.",
    }),
  ],

  seedStories: [
    makeStory({
      slug: "history-of-domestic-cats",
      title: "The Fascinating 10,000-Year History of Domestic Cats",
      category: "Cats", date: "2026-06-01", author: "Pet Historian",
      image: IMG.cat,
      excerpt: "From Egyptian temples to internet fame — how cats conquered human hearts across millennia.",
      lead: "Cats were worshipped in ancient Egypt, hunted in medieval Europe, and today rule the internet. Their journey alongside humans is one of the most remarkable partnerships in history.",
      takeaway: "Cats domesticated themselves — they chose us as much as we chose them.",
      sections: [
        { h: "Ancient origins", p: ["Archaeological evidence shows cats began living near human settlements in the Fertile Crescent around 9,500 years ago, attracted by rodents in grain stores."] },
        { h: "Egyptian reverence", p: ["In ancient Egypt, cats were sacred. Killing a cat was punishable by death. The goddess Bastet was depicted with a cat's head."] },
        { h: "Spread across the world", p: ["Roman soldiers carried cats on ships to control vermin. By the Middle Ages, cats had reached every continent except Antarctica."] },
      ],
      conclusion: "Today over 600 million cats share our homes — continuing a bond that began in the dawn of agriculture.",
    }),
    makeStory({
      slug: "history-of-domestic-dogs",
      title: "From Wolves to Woof: The Story of How Dogs Became Our Best Friends",
      category: "Dogs", date: "2026-05-25", author: "Pet Historian",
      image: IMG.dog,
      excerpt: "The incredible tale of wolf domestication and the birth of hundreds of dog breeds.",
      lead: "Dogs were the first animals humans domesticated — possibly 15,000 to 30,000 years ago. Every breed from Chihuahua to Great Dane traces back to wild wolves.",
      takeaway: "Dogs evolved alongside humans, developing an unmatched ability to read our emotions.",
      sections: [
        { h: "The wolf connection", p: ["Genetic studies confirm all dogs descend from gray wolves. The split happened when some wolves learned scavenging near human camps was easier than hunting."] },
        { h: "Working partners", p: ["Early dogs helped hunt, guarded camps, and pulled sleds. Different regions bred dogs for different jobs — herding, retrieving, guarding."] },
        { h: "Modern companions", p: ["Today there are over 340 recognized breeds. Dogs can understand hundreds of words and read human facial expressions better than any other animal."] },
      ],
      conclusion: "The bond between humans and dogs is written in our DNA — literally. Studies show both species release oxytocin when they look into each other's eyes.",
    }),
    makeStory({
      slug: "history-of-pet-parrots",
      title: "Colorful Companions: A History of Parrots as Pets",
      category: "Birds", date: "2026-05-18", author: "Pet Historian",
      image: IMG.parrot,
      excerpt: "How parrots went from tropical rainforests to royal courts and family living rooms.",
      lead: "Parrots have captivated humans for over 3,000 years. Alexander the Great reportedly brought parrots from India to Europe. Their intelligence and vivid colors made them symbols of wealth and exotic wonder.",
      takeaway: "Parrots are among the most intelligent birds — some species match the cognitive ability of a 5-year-old child.",
      sections: [
        { h: "Royal pets", p: ["European nobility kept parrots in ornate cages. Henry VIII owned an African grey. Portuguese explorers traded parrots across continents."] },
        { h: "Talking birds", p: ["The ability to mimic human speech made parrots legendary. Pirate lore popularized the image of a parrot on a shoulder — rooted in real maritime tradition."] },
      ],
      conclusion: "With proper care, parrots outlive many other pets — a commitment measured in decades, not years.",
    }),
    makeStory({
      slug: "history-of-backyard-chickens",
      title: "Murga to Backyard: The Rise of Chickens as Pets",
      category: "Birds", date: "2026-05-10", author: "Pet Historian",
      image: IMG.rooster,
      excerpt: "Chickens were domesticated 8,000 years ago. Today they're beloved backyard companions worldwide.",
      lead: "The red junglefowl of Southeast Asia is the ancestor of every chicken on Earth. What began as a food source has evolved into a global pet-keeping phenomenon.",
      takeaway: "Chickens have distinct personalities, recognize faces, and form social hierarchies — the famous 'pecking order.'",
      sections: [
        { h: "Ancient domestication", p: ["Chickens spread from Asia to Africa and Europe along trade routes. Romans used them for both eggs and divination."] },
        { h: "Backyard revolution", p: ["The urban chicken movement of the 2000s brought roosters and hens into suburban gardens. Fresh eggs and pest control made them practical pets."] },
      ],
      conclusion: "Whether you call them murga, rooster, or cockerel — chickens have earned their place in the pet world.",
    }),
    makeStory({
      slug: "history-of-pet-rabbits",
      title: "From Wild Meadows to Living Rooms: The Rabbit's Journey",
      category: "Rabbits", date: "2026-05-02", author: "Pet Historian",
      image: IMG.rabbit,
      excerpt: "How the European rabbit became one of the world's most popular small pets.",
      lead: "Monks in medieval France were among the first to keep rabbits in enclosed warrens. By the Victorian era, rabbits had hopped from the dinner table to the drawing room as cherished companions.",
      takeaway: "Rabbits are crepuscular — most active at dawn and dusk — which fits surprisingly well with human schedules.",
      sections: [
        { h: "Medieval warrens", p: ["French monks bred rabbits for meat in walled enclosures. Selective breeding produced the first color variations."] },
        { h: "Victorian pets", p: ["Queen Victoria kept rabbits as pets, popularizing them among the upper class. The 'Belgian Hare' craze of the 1890s made rabbits fashionable."] },
      ],
      conclusion: "Over 6 million pet rabbits live in homes worldwide — soft, social, and full of surprises.",
    }),
    makeStory({
      slug: "history-of-songbirds-as-pets",
      title: "Chiriya and Songbirds: A Global Tradition of Bird Keeping",
      category: "Birds", date: "2026-04-25", author: "Pet Historian",
      image: IMG.bird,
      excerpt: "From South Asian chiriya cages to European canary culture — the timeless love of songbirds.",
      lead: "Keeping small songbirds — chiriya in Urdu/Hindi, finches in English — is a tradition spanning cultures and centuries. Their songs have filled homes from Istanbul to Delhi to London.",
      takeaway: "Songbirds need flight space and companionship. A lone bird in a tiny cage is a tradition worth updating with modern welfare standards.",
      sections: [
        { h: "Cultural significance", p: ["In South Asia, keeping chiriya is a cherished hobby passed through generations. Bird markets remain vibrant cultural centers."] },
        { h: "European canaries", p: ["Canary breeding became a competitive sport in 19th-century Europe. Miners famously used canaries as early warning systems for toxic gases."] },
      ],
      conclusion: "The joy of a songbird's morning chorus connects us to a tradition as old as civilization itself.",
    }),
  ],
};
